version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - buyza-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  usuarios:
    image: dcontreras1402/ms-usuarios:latest
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=marketplace_usuarios
    networks:
      - buyza-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager

  catalogo:
    image: dcontreras1402/ms-catalogo:latest
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=buyza_catalogo
    networks:
      - buyza-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager

  ordenes:
    image: dcontreras1402/ms-ordenes:latest
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=buyza_ordenes
      - CATALOGO_SERVICE_URL=http://catalogo:3002
    networks:
      - buyza-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager

  pagos:
    image: dcontreras1402/ms-pagos:latest
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=buyza_pagos
      - CREDITO_SERVICE_URL=http://credito:3005
    networks:
      - buyza-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager

  credito:
    image: dcontreras1402/ms-credito:latest
    ports:
      - "3005:3005"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=buyza_credito
    networks:
      - buyza-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager

  frontend:
    image: dcontreras1402/ms-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - buyza-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

networks:
  buyza-net:
    driver: overlay

volumes:
  db_data:
