version: '3.8'

services:
  haproxy:
    image: haproxy:2.8
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - buyza-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - buyza-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  usuarios:
    image: dcontreras1402/ms-usuarios:latest
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_NAME=marketplace_usuarios
    networks:
      - buyza-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

  catalogo:
    image: dcontreras1402/ms-catalogo:latest
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_NAME=buyza_catalogo
    networks:
      - buyza-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

  ordenes:
    image: dcontreras1402/ms-ordenes:latest
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_NAME=buyza_ordenes
      - CATALOGO_SERVICE_URL=http://catalogo:3002
    networks:
      - buyza-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

  pagos:
    image: dcontreras1402/ms-pagos:latest
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_NAME=buyza_pagos
      - CREDITO_SERVICE_URL=http://credito:3005
    networks:
      - buyza-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

  credito:
    image: dcontreras1402/ms-credito:latest
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_NAME=buyza_credito
    networks:
      - buyza-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

  frontend:
    image: dcontreras1402/ms-frontend:latest
    networks:
      - buyza-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

networks:
  buyza-net:
    driver: overlay

volumes:
  db_data:
